name = "DynamicalSystems"
uuid = "a8e5e381-9b82-4a3e-907d-c9280a78a3a5"
authors = ["Taylor Pool <taylorpool.27@gmail.com>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
